### ISSUE TITLE
[FeaturRequest] Flexbox layout

### ISSUE THREAD

**Issue by vdawg-git** [infely/react-curse#6]
Thank you for creating this awesome library! :D 
Can you add flexbox layouts to it?
You could use like [Yoga](https://github.com/facebook/yoga) for that

**Comment by infely** [comment]
I don't have plans to do this at the moment. Take a look at [ink](https://github.com/vadimdemedes/ink) may be that is what you are looking for.

**Comment by vdawg-git** [comment]
I am coming from Ink, but it has not absolute positioning.
I decided to just learn Go, as the Charm stuff seems to be really cool

**Comment by YPetremann** [comment]
> Thats cool. I am coming from Ink though, but it has not absolute positioning. I decided to just learn Go, as the Charm stuff seems to be really cool :D

Just in case in Ink you have absolute positioning

    <Box position="absolute" marginLeft={5} marginTop={5} borderStyle="single">
